version: "2"

services:
  reader:
    image: stiller/tweeteranalyzerdemo_reader:v1

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports: 
     - "8080:15672"

  analyzer:
    image: stiller/tweeteranalyzerdemo_analyzer:v1

  aggregator:
    image: stiller/tweeteranalyzerdemo_aggregator:v1

  redis:
    image: redis:3.2.4-alpine

  result:
    image: stiller/tweeteranalyzerdemo_result:v1
    ports: 
      - "80:80"
